export default {
    LOAD_RAFFLE_TICKETS: 'LOAD_RAFFLE_TICKETS',
    LOAD_RAFFLE_TICKETS_SUCCESS: 'LOAD_RAFFLE_TICKETS_SUCCESS',
    LOAD_RAFFLE_TICKETS_FAILURE: 'LOAD_RAFFLE_TICKETS_FAILURE',
    SET_SELECTED_TICKET: 'SET_SELECTED_TICKET',
    DRAW_TICKET: 'DRAW_TICKET',
    DRAW_TICKET_SUCCESS: 'DRAW_TICKET_SUCCESS',
    DRAW_TICKET_FAILURE: 'DRAW_TICKET_FAILURE'
}